### PR TITLE
Manifest section

### PR DESCRIPTION
**Pull request by simonvaucher**
## Description
- Moved MOST field types inside the `assets, data, general, styles, rules` sections to separate sections in the documentation.
- Added for the first time (yey!) documentation for general field types - `text_input`, `file_uploader` etc.
- Deleted a few lines from `plugin_manifest_format.md` so now it's less-huge. It is still a mess, though 😬 
- Created a STANDARD TEMPLATE for field types. Hopefully it can be used later for anything field-like
 
### HOW DO I CHECK THIS MESS? 36 files? are you crazy?
- `git checkout manifest-section`
- `npm start`
- Make coffee
- Get back, sip coffee, select `ZAPP PLUGIN MANIFEST > Configuration Fields` and start checking EACH AND EVERY LINK to make sure it's not broken 😛 

## Known issues
- Probably missed a few field types!

## Screenshot
Screen Shot 2020-02-10 at 5 08 59 PM

## Checklist

* [x] PR is scoped to one task
* [ ] Tests are included
* [ ] Documentation is included

* [ ] This PR is not making any UI change
* [x] This PR is making a UI change
  * [x] Screenshot(s) included

## QA :

* required test cases:
* specific apps / plugins to test :

### CODE REVIEW

**Comment by ranmeirman** [comment]
@simonvaucher looks great. It is missing the `textarea` field type.

**Comment by simonvaucher** [comment]
> @simonvaucher looks great. It is missing the `textarea` field type.

I need to complete this with a serious "phase 2" check for all the minute and annoying differences between the fields in the `data/general/etc`. vs `custom_configuration_fields`. We can either document all those discrepancies or fix them, it's a fine balance...

**Comment by simonvaucher** [comment]
update: Added the missing `text_area` type

**Comment by simonvaucher** [comment]
@snooky23 ? @lomudi ? @guysarfatty ?

**Pull request merged**
