### PR TITLE
Addition of error monitoring plugin

### PR DESCRIPTION
**Pull request by AlexDmitryukov**
## Description
Addition of error monitoring plugin
## Checklist

* [x] PR is scoped to one task
* [ ] Tests are included
* [x] Documentation is included

* [ ] This PR is not making any UI change
* [ ] This PR is making a UI change
  * [ ] Screenshot(s) included

## QA :

* required test cases:
* specific apps / plugins to test :

### CODE REVIEW

**Comment by alexzchut** [comment]
@AlexDmitryukov https://github.com/applicaster/developer.applicaster.com/pull/317

**Comment by liviur** [comment]
iOS side looks good to me - other than previously mentioned things by @lomudi regarding a sample project mainly

**Comment by alexzchut** [comment]
@liviur  Sample project added there, I made the new app center plugin public

**Comment by liviur** [comment]
@alexzchut  - worth adding a link for the github then for the sample
In general we try to have "white label" examples here for all plugins:
https://github.com/applicaster/zapp-plugins-examples

Other then that - iOS in terms of content looks fine.
@snooky23 should give the final approval on android part

**Comment by AlexDmitryukov** [comment]
> Please add a section from which SDK version it's supported on both platforms.
> I'll check the Android side tomorrow morning.

It is specified on Android

**Comment by ranmeirman** [comment]
@snooky23 can this be merged please?

**Comment by snooky23** [comment]
@AlexDmitryukov @alexzchut - it looks great. please add just a small section per platform regarding from which minimum version we can start using it.

**Pull request merged**
